version: "3"

services:
  backend:
    image: backend
    build:
      context: ./backend
    ports:
      - 5000:5000

  frontend:
    image: webpack
    build:
      context: ./app
    ports:
      - 8080:8080
    volumes:
      - ./app:/src:rw
      - node_modules:/src/node_modules

  postgres:
    image: postgres
    build:
      context: ./postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data/db-files/
    
volumes:
  node_modules: